version: "3.8"

services:
  fastapi_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    command: /start.sh

  db:
    container_name: postgres_db
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
